[package]
name = "kleurenwiezen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bmi2 = []
debug = []

[dependencies]
ismcts = "0.2.0"
romu = "0.6.0"

[profile.release]
debug = true
overflow-checks = false
