[package]
name = "manille-master"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bmi2 = []
debug = []

[dependencies]
ismcts = "0.3.0"
rand = "0.9.0"
romu = "0.6.0"

eframe = "0.31.1"
egui_extras = { version = "0.31.1", features = ["default", "image", "file"] }
image = { version = "0.25", features = ["jpeg", "png"] } 
env_logger = { version = "0.11.6", default-features = false, features = [
    "auto-color",
    "humantime",
] }
log = "0.4.26"

[profile.release]
debug = true
overflow-checks = false
